version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: techblog_postgres_dev
    environment:
      POSTGRES_DB: techblog_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - techblog_dev_network

  redis:
    image: redis:7-alpine
    container_name: techblog_redis_dev
    ports:
      - "6379:6379"
    networks:
      - techblog_dev_network

volumes:
  postgres_dev_data:

networks:
  techblog_dev_network:
    driver: bridge